version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/server
      - /server/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
